application: academic-tenure-692
version: 1
runtime: php
api_version: 1

handlers:

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  script: /index.html

- url: /assets/(.*\.(ico|jpg|png|gif))$
  static_files: assets/\1
  upload: assets/.*\.(ico|jpg|png|gif)$
  application_readable: true

- url: /assets/(.*\.(htm|html|css|js))$
  static_files: assets/\1
  upload: assets/.*\.(htm|html|css|js)$
  application_readable: true

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$